package entry;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "btInfo_android".
 */
public class BtInfo implements Parcelable {

    private Long id;
    private String btname;
    private Integer isVisible;
    private String distance;
    private String status;
    private String btpwd;
    private String btmac;
    private Integer rssi;

    public BtInfo() {
    }

    public BtInfo(Long id) {
        this.id = id;
    }

    public BtInfo(Long id, String btname, Integer isVisible, String distance, String status, String btpwd, String btmac, Integer rssi) {
        this.id = id;
        this.btname = btname;
        this.isVisible = isVisible;
        this.distance = distance;
        this.status = status;
        this.btpwd = btpwd;
        this.btmac = btmac;
        this.rssi = rssi;
    }

    protected BtInfo(Parcel in) {
        btname = in.readString();
        distance = in.readString();
        status = in.readString();
        btpwd = in.readString();
        btmac = in.readString();
    }



    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBtname() {
        return btname;
    }

    public void setBtname(String btname) {
        this.btname = btname;
    }

    public Integer getIsVisible() {
        return isVisible;
    }

    public void setIsVisible(Integer isVisible) {
        this.isVisible = isVisible;
    }

    public String getDistance() {
        return distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getBtpwd() {
        return btpwd;
    }

    public void setBtpwd(String btpwd) {
        this.btpwd = btpwd;
    }

    public String getBtmac() {
        return btmac;
    }

    public void setBtmac(String btmac) {
        this.btmac = btmac;
    }

    public Integer getRssi() {
        return rssi;
    }

    public void setRssi(Integer rssi) {
        this.rssi = rssi;
    }

    /**
     * Describe the kinds of special objects contained in this Parcelable's
     * marshalled representation.
     *
     * @return a bitmask indicating the set of special object types marshalled
     * by the Parcelable.
     */
    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * Flatten this object in to a Parcel.
     *
     * @param dest  The Parcel in which the object should be written.
     * @param flags Additional flags about how the object should be written.
     *              May be 0 or {@link #PARCELABLE_WRITE_RETURN_VALUE}.
     */
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(btname);
        dest.writeString(distance);
        dest.writeString(status);
        dest.writeString(btpwd);
        dest.writeString(btmac);
    }

    public static final Creator<BtInfo> CREATOR=new Creator<BtInfo>() {
        @Override
        public BtInfo createFromParcel(Parcel source) {
            BtInfo btInfo=new BtInfo();
            btInfo.setId(source.readLong());
            btInfo.setRssi(source.readInt());
            btInfo.setIsVisible(source.readInt());
            btInfo.setBtmac(source.readString());
            btInfo.setBtname(source.readString());
            btInfo.setBtpwd(source.readString());
            btInfo.setDistance(source.readString());
            btInfo.setStatus(source.readString());
            return btInfo;
        }

        @Override
        public BtInfo[] newArray(int size) {
            return new BtInfo[size];
        }
    };
}
