package entry;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import entry.BtInfo;
import entry.User;

import entry.BtInfoDao;
import entry.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig btInfoDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BtInfoDao btInfoDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        btInfoDaoConfig = daoConfigMap.get(BtInfoDao.class).clone();
        btInfoDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        btInfoDao = new BtInfoDao(btInfoDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(BtInfo.class, btInfoDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        btInfoDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public BtInfoDao getBtInfoDao() {
        return btInfoDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
