package entry;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "user_android".
 */
public class User {

    private Long id;
    private String username;
    private String userpwd;
    private String avatar;
    private Integer autologin;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String username, String userpwd, String avatar, Integer autologin) {
        this.id = id;
        this.username = username;
        this.userpwd = userpwd;
        this.avatar = avatar;
        this.autologin = autologin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUserpwd() {
        return userpwd;
    }

    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getAutologin() {
        return autologin;
    }

    public void setAutologin(Integer autologin) {
        this.autologin = autologin;
    }

}
